Better way to check for pgrx version from cargo tree

diff --git a/plrust/build b/plrust/build
--- a/plrust/build
+++ b/plrust/build
@@ -52,11 +52,18 @@ fi
 cargo update -p pgrx
 cargo fetch
 if [ "$CI" != true ]; then
-    PGRX_VERSION=$(cargo tree --package plrust | grep -P "\s+pgrx\s+" | head -n 1| cut -f2- -dv)
-    echo "Installing cargo-pgrx version $PGRX_VERSION"
-    cargo install cargo-pgrx \
-        --version "$PGRX_VERSION" \
-        --locked # use the Cargo.lock in the pgrx repo
+    # Attempt to get pgrx version from cargo tree. Looking for a pattern such as "pgrx v0.10.0"
+    PGRX_VERSION=$(cargo tree | grep -E "\s*pgrx\s+v[0-9]+\.[0-9]+\.[0-9]+" | head -n 1 | cut -f2- -dv)
+
+    if [ -z "$PGRX_VERSION" ]; then
+        echo "Could not determine pgrx version from 'cargo tree'!"
+        exit 1
+    else
+        echo "Installing cargo-pgrx version $PGRX_VERSION"
+        cargo install cargo-pgrx \
+            --version "$PGRX_VERSION" \
+            --locked # use the Cargo.lock in the pgrx repo
+    fi
 fi
 
 # Don't need to run cargo pgrx init: user might already have set it up,
