Extract cargo-pgx install to script, re-enable for testing

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -115,20 +115,11 @@ jobs:
     - name: Print sccache stats (before build)
       run: sccache --show-stats
 
+    # See <plrust-root>/.github/scripts/install_cargo_pgx.sh for more details
     - name: Install cargo-pgx defined in plrust/Cargo.toml
       run: |
-        #!/bin/bash
-
-        set -o pipefail
-        set -e
-
-        if TARGET_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[]|select(.name=="pgx")|.version'); then
-          echo "Installing/upgrading cargo-pgx to version $TARGET_VERSION"
-          cargo install cargo-pgx --version "$TARGET_VERSION"
-        else
-          echo "Could not determine cargo-pgx version to install."
-          exit 1
-        fi
+        . $WORK_DIR/.github/scripts/install_cargo_pgx.sh
+        install_cargo_pgx
 
     - name: Run cargo pgx init for PG14
       run: cargo pgx init --pg14 $(which pg_config)
@@ -163,151 +154,143 @@ jobs:
         sccache_dirs=($HOME/.cache/sccache)
         savecache $sccache_key "${sccache_dirs[@]}"
 
-  # plrust_tests:
-  #   name: tests
-  #   runs-on: ${{ matrix.os }}
-  #   if: "!contains(github.event.head_commit.message, 'nogha')"
+  plrust_tests:
+    name: tests
+    runs-on: ${{ matrix.os }}
+    if: "!contains(github.event.head_commit.message, 'nogha')"
 
-  #   strategy:
-  #     matrix:
-  #       # version: ["pg13", "pg14", "pg15"]
-  #       version: ["pg15"]
-  #       os: ["ubuntu-20.04"]
-  #       # it would be nice to other contributors to return "macos-11" to the above array
-  #     fail-fast: false
+    strategy:
+      matrix:
+        # version: ["pg13", "pg14", "pg15"]
+        version: ["pg15"]
+        os: ["ubuntu-20.04"]
+        # it would be nice to other contributors to return "macos-11" to the above array
+      fail-fast: false
 
-  #   steps:
-  #   - uses: actions/checkout@v3
+    steps:
+    - uses: actions/checkout@v3
 
-  #   - name: Set up (Linux) prerequisites and environment
-  #     if: matrix.os == 'ubuntu-20.04'
-  #     run: |
-  #       echo ""
+    - name: Set up (Linux) prerequisites and environment
+      if: matrix.os == 'ubuntu-20.04'
+      run: |
+        echo ""
 
-  #       echo "----- Set up dynamic variables -----"
-  #       export PG_VER=$(echo ${{ matrix.version }} | cut -c 3-)
-  #       echo "PG_VER=$PG_VER" >> $GITHUB_ENV
-  #       echo "MAKEFLAGS=$MAKEFLAGS -j $(grep -c ^processor /proc/cpuinfo)" >> $GITHUB_ENV
-  #       cat $GITHUB_ENV
-  #       echo ""
+        echo "----- Set up dynamic variables -----"
+        export PG_VER=$(echo ${{ matrix.version }} | cut -c 3-)
+        echo "PG_VER=$PG_VER" >> $GITHUB_ENV
+        echo "MAKEFLAGS=$MAKEFLAGS -j $(grep -c ^processor /proc/cpuinfo)" >> $GITHUB_ENV
+        cat $GITHUB_ENV
+        echo ""
 
-  #       echo "----- Remove old postgres -----"
-  #       sudo apt remove -y postgres*
-  #       echo ""
+        echo "----- Remove old postgres -----"
+        sudo apt remove -y postgres*
+        echo ""
 
-  #       echo "----- Set up PostgreSQL Apt repository -----"
-  #       sudo apt-get install -y wget gnupg
-  #       sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
-  #       wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
-  #       sudo apt-get update -y -qq --fix-missing
-  #       echo ""
+        echo "----- Set up PostgreSQL Apt repository -----"
+        sudo apt-get install -y wget gnupg
+        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
+        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
+        sudo apt-get update -y -qq --fix-missing
+        echo ""
 
-  #       echo "----- Install system dependencies and PostgreSQL version $PG_VER -----"
-  #       sudo apt-get install -y \
-  #         clang-10 \
-  #         llvm-10 \
-  #         clang \
-  #         gcc \
-  #         make \
-  #         build-essential \
-  #         libz-dev \
-  #         zlib1g-dev \
-  #         strace \
-  #         libssl-dev \
-  #         pkg-config \
-  #         postgresql-$PG_VER \
-  #         postgresql-server-dev-$PG_VER
-  #       echo ""
+        echo "----- Install system dependencies and PostgreSQL version $PG_VER -----"
+        sudo apt-get install -y \
+          clang-10 \
+          llvm-10 \
+          clang \
+          gcc \
+          make \
+          build-essential \
+          libz-dev \
+          zlib1g-dev \
+          strace \
+          libssl-dev \
+          pkg-config \
+          postgresql-$PG_VER \
+          postgresql-server-dev-$PG_VER
+        echo ""
 
-  #       echo "----- Set up Postgres permissions -----"
-  #       sudo chmod a+rwx `/usr/lib/postgresql/$PG_VER/bin/pg_config --pkglibdir` `/usr/lib/postgresql/$PG_VER/bin/pg_config --sharedir`/extension /var/run/postgresql/
-  #       echo ""
+        echo "----- Set up Postgres permissions -----"
+        sudo chmod a+rwx `/usr/lib/postgresql/$PG_VER/bin/pg_config --pkglibdir` `/usr/lib/postgresql/$PG_VER/bin/pg_config --sharedir`/extension /var/run/postgresql/
+        echo ""
 
-  #       echo "----- Print env -----"
-  #       env
-  #       echo ""
+        echo "----- Print env -----"
+        env
+        echo ""
 
-  #       echo "----- Get cargo version -----"
-  #       cargo --version
-  #       echo ""
+        echo "----- Get cargo version -----"
+        cargo --version
+        echo ""
 
-  #   - name: Set up (Mac) prerequisites and environment
-  #     if: matrix.os == 'macos-11'
-  #     run: |
-  #       echo ""
+    - name: Set up (Mac) prerequisites and environment
+      if: matrix.os == 'macos-11'
+      run: |
+        echo ""
 
-  #       # https://stackoverflow.com/questions/57968497/how-do-i-set-an-env-var-with-a-bash-expression-in-github-actions/57969570#57969570
-  #       echo "----- Getting pre-installed Postgres major version -----"
-  #       PG_VER=$(pg_config --version | awk '{split($2,a,"."); print a[1]}')
-  #       echo "PG_VER=$PG_VER" >> $GITHUB_ENV
-  #       cat $GITHUB_ENV
+        # https://stackoverflow.com/questions/57968497/how-do-i-set-an-env-var-with-a-bash-expression-in-github-actions/57969570#57969570
+        echo "----- Getting pre-installed Postgres major version -----"
+        PG_VER=$(pg_config --version | awk '{split($2,a,"."); print a[1]}')
+        echo "PG_VER=$PG_VER" >> $GITHUB_ENV
+        cat $GITHUB_ENV
 
-  #       echo "----- Installing yq so .toml files can be parsed and queried -----"
-  #       pip3 install yq
-  #       echo ""
+        echo "----- Installing yq so .toml files can be parsed and queried -----"
+        pip3 install yq
+        echo ""
 
-  #       echo "----- Setting up RUSTFLAGS found in .cargo/config -----"
-  #       echo "RUSTFLAGS=$RUSTFLAGS $(tomlq --raw-output '.build.rustflags | join(" ")' .cargo/config)" >> $GITHUB_ENV
-  #       cat $GITHUB_ENV
-  #       echo ""
+        echo "----- Setting up RUSTFLAGS found in .cargo/config -----"
+        echo "RUSTFLAGS=$RUSTFLAGS $(tomlq --raw-output '.build.rustflags | join(" ")' .cargo/config)" >> $GITHUB_ENV
+        cat $GITHUB_ENV
+        echo ""
 
-  #       echo "----- Set up Postgres permissions -----"
-  #       sudo chmod a+rwx `$(which pg_config) --pkglibdir` `$(which pg_config) --sharedir`/extension
-  #       ls -lath `$(which pg_config) --pkglibdir` `$(which pg_config) --sharedir`/extension
-  #       echo ""
+        echo "----- Set up Postgres permissions -----"
+        sudo chmod a+rwx `$(which pg_config) --pkglibdir` `$(which pg_config) --sharedir`/extension
+        ls -lath `$(which pg_config) --pkglibdir` `$(which pg_config) --sharedir`/extension
+        echo ""
 
-  #       echo "----- Output Cargo version -----"
-  #       cargo --version
-  #       echo ""
+        echo "----- Output Cargo version -----"
+        cargo --version
+        echo ""
 
-  #       echo "----- Outputting env -----"
-  #       env
-  #       echo ""
+        echo "----- Outputting env -----"
+        env
+        echo ""
 
-  #   - name: Cache cargo registry
-  #     uses: actions/cache@v3
-  #     continue-on-error: false
-  #     with:
-  #       path: |
-  #         ~/.cargo
-  #         target/
-  #       key: v0-${{ runner.os }}-${{ hashFiles('**/Cargo.lock', '.github/workflows/ci.yml') }}
+    - name: Cache cargo registry
+      uses: actions/cache@v3
+      continue-on-error: false
+      with:
+        path: |
+          ~/.cargo
+          target/
+        key: v0-${{ runner.os }}-${{ hashFiles('**/Cargo.lock', '.github/workflows/ci.yml') }}
 
-  #   - name: Install cargo-pgx defined in plrust/Cargo.toml
-  #     run: |
-  #       #!/bin/bash
+    # See <plrust-root>/.github/scripts/install_cargo_pgx.sh for more details
+    - name: Install cargo-pgx defined in plrust/Cargo.toml
+      run: |
+        . $WORK_DIR/.github/scripts/install_cargo_pgx.sh
+        install_cargo_pgx
 
-  #       set -o pipefail
-  #       set -e
+    - name: Run 'cargo pgx init' against system-level ${{ matrix.version }}
+      run: cargo pgx init --pg$PG_VER $(which pg_config)
 
-  #       if TARGET_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[]|select(.name=="pgx")|.version'); then
-  #         echo "Installing/upgrading cargo-pgx to version $TARGET_VERSION"
-  #         cargo install cargo-pgx --version "$TARGET_VERSION"
-  #       else
-  #         echo "Could not determine cargo-pgx version to install."
-  #         exit 1
-  #       fi
+    - name: Test PL/rust as "untrusted"
+      run: cargo test --all --features "pg$PG_VER" --no-default-features
 
-  #   - name: Run 'cargo pgx init' against system-level ${{ matrix.version }}
-  #     run: cargo pgx init --pg$PG_VER $(which pg_config)
+    - name: Test PL/rust as "trusted" (inc. postgrestd)
+      run: cd plrust && STD_TARGETS="x86_64-postgres-linux-gnu" ./build
 
-  #   - name: Test PL/rust as "untrusted"
-  #     run: cargo test --all --features "pg$PG_VER" --no-default-features
-
-  #   - name: Test PL/rust as "trusted" (inc. postgrestd)
-  #     run: cd plrust && STD_TARGETS="x86_64-postgres-linux-gnu" ./build
-
-  #   # # Attempt to make the cache payload slightly smaller.
-  #   # - name: Clean up built PGX files
-  #   #   run: |
-  #   #     cd target/debug/deps/
-  #   #     for built_file in $(find * -type f -executable -print | grep -v "\.so$"); do
-  #   #       base_name=$(echo $built_file | cut -d- -f1);
-  #   #       for basefile in "$base_name".*; do
-  #   #         [ -f "$basefile" ] || continue;
-  #   #         echo "Removing $basefile"
-  #   #         rm $basefile
-  #   #       done;
-  #   #       echo "Removing $built_file"
-  #   #       rm $built_file
-  #   #     done
+    # # Maybe this is not necessary if we switch to sccache?
+    # # Attempt to make the cache payload slightly smaller.
+    # - name: Clean up built PGX files
+    #   run: |
+    #     cd target/debug/deps/
+    #     for built_file in $(find * -type f -executable -print | grep -v "\.so$"); do
+    #       base_name=$(echo $built_file | cut -d- -f1);
+    #       for basefile in "$base_name".*; do
+    #         [ -f "$basefile" ] || continue;
+    #         echo "Removing $basefile"
+    #         rm $basefile
+    #       done;
+    #       echo "Removing $built_file"
+    #       rm $built_file
+    #     done
