First attempt

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,152 +10,151 @@ on:
 
 env:
   RUST_BACKTRACE: 1
-  CARGO_PGX_VERSION: "0.6.0"
   # CARGO_LOG: cargo::core::compiler::fingerprint=info # Uncomment this to output compiler fingerprint info
 
 jobs:
-  plrust_tests_arm64:
-    name: aarch64 tests (pg14, amzn2)
-    runs-on: [self-hosted, linux, ARM64, plrust]
+  # plrust_tests_arm64:
+  #   name: aarch64 tests (pg14, amzn2)
+  #   runs-on: [self-hosted, linux, ARM64, plrust]
 
-    env:
-      RUSTC_WRAPPER: sccache
-      SCCACHE_DIR: /home/ec2-user/.cache/sccache
-      CACHE_KEY_VERSION: v0
-      SCCACHE_CACHE_SIZE: 20G
-      WORK_DIR: /home/ec2-user/actions-runner/_work/plrust/plrust
-      ARTIFACT_USER_AWS_PROFILE: artifact-user
-      AWS_CACHE_BUCKET: tcdi-ci-plrust-build-cache.private
+  #   env:
+  #     RUSTC_WRAPPER: sccache
+  #     SCCACHE_DIR: /home/ec2-user/.cache/sccache
+  #     CACHE_KEY_VERSION: v0
+  #     SCCACHE_CACHE_SIZE: 20G
+  #     WORK_DIR: /home/ec2-user/actions-runner/_work/plrust/plrust
+  #     ARTIFACT_USER_AWS_PROFILE: artifact-user
+  #     AWS_CACHE_BUCKET: tcdi-ci-plrust-build-cache.private
 
-    steps:
-    - uses: actions/checkout@v3
+  #   steps:
+  #   - uses: actions/checkout@v3
 
-    - name: Generate cache filename checksum
-      run: |
-        cd $WORK_DIR
-        shopt -s globstar
-        checksum=$(cat **/Cargo.lock .github/workflows/ci.yml | sha256sum | awk '{print $1}')
-        echo "CACHE_KEY_CHECKSUM=$checksum" >> $GITHUB_ENV
+  #   - name: Generate cache filename checksum
+  #     run: |
+  #       cd $WORK_DIR
+  #       shopt -s globstar
+  #       checksum=$(cat **/Cargo.lock .github/workflows/ci.yml | sha256sum | awk '{print $1}')
+  #       echo "CACHE_KEY_CHECKSUM=$checksum" >> $GITHUB_ENV
 
-    - name: Set up (Linux) prerequisites and environment
-      run: |
-        echo ""
-        echo "----- Print kernel info -----"
-        uname -a
-        echo ""
+  #   - name: Set up (Linux) prerequisites and environment
+  #     run: |
+  #       echo ""
+  #       echo "----- Print kernel info -----"
+  #       uname -a
+  #       echo ""
 
-        echo "----- Set up dynamic variables -----"
-        echo "PG_VER=14" >> $GITHUB_ENV
-        echo "MAKEFLAGS=$MAKEFLAGS -j $(grep -c ^processor /proc/cpuinfo)" >> $GITHUB_ENV
-        echo "RUSTUP_HOME=$HOME/.rustup" >> $GITHUB_ENV
-        echo "PATH=$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
-        cat $GITHUB_ENV
-        echo ""
+  #       echo "----- Set up dynamic variables -----"
+  #       echo "PG_VER=14" >> $GITHUB_ENV
+  #       echo "MAKEFLAGS=$MAKEFLAGS -j $(grep -c ^processor /proc/cpuinfo)" >> $GITHUB_ENV
+  #       echo "RUSTUP_HOME=$HOME/.rustup" >> $GITHUB_ENV
+  #       echo "PATH=$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
+  #       cat $GITHUB_ENV
+  #       echo ""
 
-        echo "----- Install system dependencies -----"
-        sudo amazon-linux-extras enable postgresql14
-        sudo yum clean metadata
+  #       echo "----- Install system dependencies -----"
+  #       sudo amazon-linux-extras enable postgresql14
+  #       sudo yum clean metadata
 
-        sudo yum install -y \
-          libpq \
-          libpq-devel \
-          postgresql \
-          postgresql-server \
-          postgresql-server-devel \
-          openssl \
-          openssl-devel \
-          bison \
-          flex \
-          readline \
-          readline-devel \
-          clang
-        echo ""
+  #       sudo yum install -y \
+  #         libpq \
+  #         libpq-devel \
+  #         postgresql \
+  #         postgresql-server \
+  #         postgresql-server-devel \
+  #         openssl \
+  #         openssl-devel \
+  #         bison \
+  #         flex \
+  #         readline \
+  #         readline-devel \
+  #         clang
+  #       echo ""
 
-        echo "----- Set postgres permissions -----"
-        sudo chmod a+rwx `$(which pg_config) --pkglibdir` `$(which pg_config) --sharedir`/extension
-        echo ""
+  #       echo "----- Set postgres permissions -----"
+  #       sudo chmod a+rwx `$(which pg_config) --pkglibdir` `$(which pg_config) --sharedir`/extension
+  #       echo ""
 
-        echo "----- Install sccache -----"
-        mkdir -p $HOME/.local/bin
-        curl -L https://github.com/mozilla/sccache/releases/download/v0.3.0/sccache-v0.3.0-aarch64-unknown-linux-musl.tar.gz | tar xz
-        mv -f sccache-v0.3.0-aarch64-unknown-linux-musl/sccache $HOME/.local/bin/sccache
-        chmod +x $HOME/.local/bin/sccache
-        echo "$HOME/.local/bin" >> $GITHUB_PATH
-        export PATH="$HOME/.local/bin:$PATH"
-        echo 'SCCACHE_CACHE_SIZE="20G"' >> $GITHUB_ENV
-        mkdir -p $HOME/.cache/sccache
-        echo ""
+  #       echo "----- Install sccache -----"
+  #       mkdir -p $HOME/.local/bin
+  #       curl -L https://github.com/mozilla/sccache/releases/download/v0.3.0/sccache-v0.3.0-aarch64-unknown-linux-musl.tar.gz | tar xz
+  #       mv -f sccache-v0.3.0-aarch64-unknown-linux-musl/sccache $HOME/.local/bin/sccache
+  #       chmod +x $HOME/.local/bin/sccache
+  #       echo "$HOME/.local/bin" >> $GITHUB_PATH
+  #       export PATH="$HOME/.local/bin:$PATH"
+  #       echo 'SCCACHE_CACHE_SIZE="20G"' >> $GITHUB_ENV
+  #       mkdir -p $HOME/.cache/sccache
+  #       echo ""
 
-        echo "----- Create artifacts directory -----"
-        mkdir -p $HOME/artifacts
-        echo ""
+  #       echo "----- Create artifacts directory -----"
+  #       mkdir -p $HOME/artifacts
+  #       echo ""
 
-        echo "----- Install rust via rustup -----"
-        export RUSTUP_HOME="$HOME/.rustup"
-        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
-        source "$HOME/.cargo/env"
-        cargo --version
+  #       echo "----- Install rust via rustup -----"
+  #       export RUSTUP_HOME="$HOME/.rustup"
+  #       curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+  #       source "$HOME/.cargo/env"
+  #       cargo --version
 
-    - name: Load Cargo cache if available
-      run: |
-        # See <plrust-root>/.github/scripts/load_cache.sh for more details
-        . $WORK_DIR/.github/scripts/load_cache.sh
-        cargo_cache_key="plrust-arm64-cargo-cache-$CACHE_KEY_VERSION-$CACHE_KEY_CHECKSUM.tar.lz4"
-        loadcache $cargo_cache_key
+  #   - name: Load Cargo cache if available
+  #     run: |
+  #       # See <plrust-root>/.github/scripts/load_cache.sh for more details
+  #       . $WORK_DIR/.github/scripts/load_cache.sh
+  #       cargo_cache_key="plrust-arm64-cargo-cache-$CACHE_KEY_VERSION-$CACHE_KEY_CHECKSUM.tar.lz4"
+  #       loadcache $cargo_cache_key
 
-    - name: Load sccache cache if available
-      run: |
-        # See <plrust-root>/.github/scripts/load_cache.sh for more details
-        . $WORK_DIR/.github/scripts/load_cache.sh
-        sccache_key="plrust-arm64-sccache-cache-$CACHE_KEY_VERSION-$CACHE_KEY_CHECKSUM.tar.lz4"
-        loadcache $sccache_key
+  #   - name: Load sccache cache if available
+  #     run: |
+  #       # See <plrust-root>/.github/scripts/load_cache.sh for more details
+  #       . $WORK_DIR/.github/scripts/load_cache.sh
+  #       sccache_key="plrust-arm64-sccache-cache-$CACHE_KEY_VERSION-$CACHE_KEY_CHECKSUM.tar.lz4"
+  #       loadcache $sccache_key
 
-    - name: Start sccache server
-      run: sccache --start-server
+  #   - name: Start sccache server
+  #     run: sccache --start-server
 
-    - name: Print sccache stats (before build)
-      run: sccache --show-stats
+  #   - name: Print sccache stats (before build)
+  #     run: sccache --show-stats
 
-    - name: Install cargo-pgx
-      continue-on-error: true # We might have it.
-      run: cargo install cargo-pgx --git "https://github.com/tcdi/pgx" --branch "develop" --force
-      # run: cargo install cargo-pgx --locked --version "${CARGO_PGX_VERSION}"
+  #   - name: Install cargo-pgx
+  #     continue-on-error: true # We might have it.
+  #     run: cargo install cargo-pgx --git "https://github.com/tcdi/pgx" --branch "develop" --force
+  #     # run: cargo install cargo-pgx --locked --version "${CARGO_PGX_VERSION}"
 
-    - name: Run cargo pgx init for PG14
-      run: cargo pgx init --pg14 $(which pg_config)
+  #   - name: Run cargo pgx init for PG14
+  #     run: cargo pgx init --pg14 $(which pg_config)
 
-    - name: Test PL/rust as "untrusted"
-      run: cargo test --all --features "pg$PG_VER" --no-default-features
+  #   - name: Test PL/rust as "untrusted"
+  #     run: cargo test --all --features "pg$PG_VER" --no-default-features
 
-    - name: Test PL/rust as "trusted" (inc. postgrestd)
-      run: cd plrust && STD_TARGETS="aarch64-postgres-linux-gnu" ./build
+  #   - name: Test PL/rust as "trusted" (inc. postgrestd)
+  #     run: cd plrust && STD_TARGETS="aarch64-postgres-linux-gnu" ./build
 
-    - name: Print sccache stats (after build)
-      run: sccache --show-stats
+  #   - name: Print sccache stats (after build)
+  #     run: sccache --show-stats
 
-    - name: Stop sccache server
-      run: sccache --stop-server || true
+  #   - name: Stop sccache server
+  #     run: sccache --stop-server || true
 
-    - name: Store Cargo cache if applicable
-      run: |
-        . $WORK_DIR/.github/scripts/save_cache.sh
-        # See <plrust-root>/.github/scripts/save_cache.sh for more details
-        cargo_cache_key="plrust-arm64-cargo-cache-$CACHE_KEY_VERSION-$CACHE_KEY_CHECKSUM.tar.lz4"
-        cargo_dirs=( \
-            $HOME/.cargo/bin \
-            $HOME/.cargo/registry/index \
-            $HOME/.cargo/registry/cache/ \
-            $HOME/.cargo/git/db \
-        )
-        savecache $cargo_cache_key "${cargo_dirs[@]}"
+  #   - name: Store Cargo cache if applicable
+  #     run: |
+  #       . $WORK_DIR/.github/scripts/save_cache.sh
+  #       # See <plrust-root>/.github/scripts/save_cache.sh for more details
+  #       cargo_cache_key="plrust-arm64-cargo-cache-$CACHE_KEY_VERSION-$CACHE_KEY_CHECKSUM.tar.lz4"
+  #       cargo_dirs=( \
+  #           $HOME/.cargo/bin \
+  #           $HOME/.cargo/registry/index \
+  #           $HOME/.cargo/registry/cache/ \
+  #           $HOME/.cargo/git/db \
+  #       )
+  #       savecache $cargo_cache_key "${cargo_dirs[@]}"
 
-    - name: Store sccache if applicable
-      run: |
-        # See <plrust-root>/.github/scripts/save_cache.sh for more details
-        . $WORK_DIR/.github/scripts/save_cache.sh
-        sccache_key="plrust-arm64-sccache-cache-$CACHE_KEY_VERSION-$CACHE_KEY_CHECKSUM.tar.lz4"
-        sccache_dirs=($HOME/.cache/sccache)
-        savecache $sccache_key "${sccache_dirs[@]}"
+  #   - name: Store sccache if applicable
+  #     run: |
+  #       # See <plrust-root>/.github/scripts/save_cache.sh for more details
+  #       . $WORK_DIR/.github/scripts/save_cache.sh
+  #       sccache_key="plrust-arm64-sccache-cache-$CACHE_KEY_VERSION-$CACHE_KEY_CHECKSUM.tar.lz4"
+  #       sccache_dirs=($HOME/.cache/sccache)
+  #       savecache $sccache_key "${sccache_dirs[@]}"
 
   plrust_tests:
     name: tests
@@ -164,7 +163,8 @@ jobs:
 
     strategy:
       matrix:
-        version: ["pg13", "pg14", "pg15"]
+        # version: ["pg13", "pg14", "pg15"]
+        version: ["pg15"]
         os: ["ubuntu-20.04"]
         # it would be nice to other contributors to return "macos-11" to the above array
       fail-fast: false
@@ -269,10 +269,18 @@ jobs:
           target/
         key: v0-${{ runner.os }}-${{ hashFiles('**/Cargo.lock', '.github/workflows/tests.yml') }}
 
-    - name: Install cargo-pgx
-      continue-on-error: true # We might have it.
-      run: cargo install cargo-pgx --git "https://github.com/tcdi/pgx" --branch "develop" --force
-      # run: cargo install cargo-pgx --locked --version "${CARGO_PGX_VERSION}"
+    - name: Install cargo-pgx defined in plrust/Cargo.toml
+      # continue-on-error: true # We might have it.
+      run: |
+        set -ex
+        export CARGO_PGX_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[]|select(.name=="pgx")|.version')
+
+        if [ -z "$CARGO_PGX_VERSION" ]; then
+          echo "Could not parse cargo-pgx version from plrust metadata file. Cannot continue"
+          exit 1
+        fi
+
+        cargo install cargo-pgx --version $CARGO_PGX_VERSION
 
     - name: Run 'cargo pgx init' against system-level ${{ matrix.version }}
       run: cargo pgx init --pg$PG_VER $(which pg_config)
